# Generated by Django 5.1.4 on 2025-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo_review', '0003_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
