# Generated by Django 5.1.4 on 2025-02-21 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo_review', '0005_review_unique_review_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(choices=[('LI', 'Litres'), ('OZ', 'Ozon')], default='LI', max_length=50)),
                ('url', models.URLField(unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='robo_review.book')),
            ],
        ),
    ]
